"""empty message

Revision ID: 7b12a99ba99e
Revises: d88039d157e7
Create Date: 2018-03-09 01:11:40.954857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b12a99ba99e'
down_revision = 'd88039d157e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('article', 'contain')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('contain', mysql.TEXT(), nullable=False))
    op.drop_column('article', 'content')
    # ### end Alembic commands ###
